version: "3"
services:
  app:
    container_name: struct-graphql
    restart: always
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://balzua:testdb56@ds337377.mlab.com:37377/struct-graphql