version: "3"
services:
  app:
    container_name: struct-graphql
    restart: always
    build: ./
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"
  mongo-seed:
    build: ./mongo
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27107:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
    